# 此处为邮箱头像的url
avatar: 

# 标题下的链接
links:
#  Github: https://github.com
#  About: /about

# Google Analytics
ga: ''
# Baidu Analytics
bt: 
# search verify
google: 
baidu: 
bing: 

# footer
footer: ''

# DisqusJS
disqusjs:
  shortname: 
  sitename: 
  api: 
  apikey: 
  admin:
  adminlabel: 

# Valine
valine:
  app_id: 
  app_key: 
  visitor: 

# 仓库编辑
github:
  username:
  repo: 
  branches: